### ISSUE TITLE
时区问题

### ISSUE THREAD

**Issue by mapleafly** [lcux/antchain.xyz#1]
首页里面 区块信息   交易信息两大板块，选择一条信息点进去，看到的时间和现实时间整整少8小时。
奇怪的是，地址信息板块点进去，显示的时间是一致的。

可能没有关系，但还是说明一下，我在中国，win10  utc +8  chrome

**Comment by lcux** [comment]
感谢！修改了。

**Comment by mapleafly** [comment]
还没有在生产环境修改吗？好像问题依旧

**Comment by lcux** [comment]
后续版本有较大改动，我想一起修改吧。
